=== 用户和用户组

> /etc/passwd, /etc/shadow, /etc/group 三个洗头膏文件包含用户及用户组的配置

==== useradd *option username*

> useradd -d /home/ycourlee -m sam -g main -G root

- useradd –d /home/sam -m sam

  新建用户 sam, -d 指明它的home目录, -m 表示目录不存在则创建.

- useradd -s /bin/sh -g group –G adm,root gem

  新建用户gem, -s 指定shell文件, 即用户的登陆shell, -g 指定主组, -G 指定附加组

option 有:

- -c comment 指定一段注释性描述
- -d 目录 指定用户主目录，如果此目录不存在，则同时使用-m选项，可以创建主目录
- -g 用户组 指定用户所属的用户组
- -G 用户组，用户组 指定用户所属的附加组
- -s Shell文件 指定用户的登录Shell
- -u 用户号 指定用户的用户号，如果同时有-o选项，则可以重复使用其他用户的标识号

==== userdel *option username*

> userdel -r ycourlee

- -r 表示一同删除用户home目录

==== usermod *option username*

> usermod -d /home/y -m ycourlee

option 同 useradd 的, 意义也相同, 有些系统还有 -l newUsername

==== passwd *option username*

> passwd

option:

- -l 锁定口令，即禁用账号。
- -u 口令解锁。
- -d 使账号无口令。
- -f 强迫用户下次登录时修改口令。

如果*默认用户名*，则*修改当前用户*的口令。

普通用户修改自己的口令时，passwd命令会先询问原口令，验证后再要求用户输入两遍新口令，如果两次输入的口令一致，则将这个口令指定给用户；而超级用户为用户指定口令时，就不需要知道原口令。

为用户指定空口令时，执行下列形式的命令：

[source,bash,indent=0]
----
$ passwd -d sam
----

此命令将用户 sam 的口令删除，这样用户 sam 下一次登录时，系统就不再允许该用户登录了。

passwd 命令还可以用 -l(lock) 选项锁定某一用户，使其不能登录，例如：

[source,bash,indent=0]
----
$ passwd -l sam
----

- [ ] group about

上文from https://www.runoob.com/linux/linux-user-manage.html[Linux用户管理]
