version: "2"
services:
  nacos-service:
    image: yooonn/nacos-service:1.0.0-SNAPSHOT
    container_name: nacos-service
    environment:
      - NACOS_SERVER_ADDR=nacos-standalone:8849
      - REDIS_SERVER_ADDR=nacos-service-redis4014
      - REDIS_SERVER_PORT=7379
      - DATASOURCE_HOST=mysql
      - DATASOURCE_PORT=3306
      - DATASOURCE_PARAM=autoReconnect=true&autoUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=10000&socketTimeout=10000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    ports:
      - "9000:8000"
    networks:
      - nacos-common

  nacos-service2:
    image: yooonn/nacos-service:1.0.0-SNAPSHOT
    container_name: nacos-service2
    environment:
      - NACOS_SERVER_ADDR=nacos-standalone:8849
      - REDIS_SERVER_ADDR=nacos-service-redis4014
      - REDIS_SERVER_PORT=7379
      - DATASOURCE_HOST=mysql
      - DATASOURCE_PORT=3306
      - DATASOURCE_PARAM=autoReconnect=true&autoUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=10000&socketTimeout=10000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    ports:
      - "9001:8000"
    networks:
      - nacos-common

networks:
  nacos-common:
    driver: bridge