version: "2"
services:
  nacos-service:
    image: yooonn/ex-nacos-service:1.0.0-SNAPSHOT
    container_name: nacos-service
    environment:
      - NACOS_SERVER_ADDR=nacos-standalone:8849
      - REDIS_SERVER_ADDR=nacos-service-redis4014
      - REDIS_SERVER_PORT=7379
      - DATASOURCE_HOST=mysql
      - DATASOURCE_PORT=3306
      - DATASOURCE_PARAM=autoReconnect=true&autoUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=10000&socketTimeout=10000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    ports:
      - "9000:8000"
    networks:
      - nacos-common
    depends_on:
      nacos:
        condition: service_started
      nacos-service-redis:
        condition: service_started
      nacos-service-mysql:
        condition: service_started

  nacos-service2:
    image: yooonn/ex-nacos-service:1.0.0-SNAPSHOT
    container_name: nacos-service2
    environment:
      - NACOS_SERVER_ADDR=nacos-standalone:8849
      - REDIS_SERVER_ADDR=nacos-service-redis4014
      - REDIS_SERVER_PORT=7379
      - DATASOURCE_HOST=mysql
      - DATASOURCE_PORT=3306
      - DATASOURCE_PARAM=autoReconnect=true&autoUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&connectTimeout=10000&socketTimeout=10000&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    ports:
      - "9001:8000"
    networks:
      - nacos-common
    depends_on:
      nacos:
        condition: service_started
      nacos-service-redis:
        condition: service_started
      nacos-service-mysql:
        condition: service_started

  nacos-service-redis:
    image: redis:4.0.14-alpine
    container_name: nacos-service-redis4014
    command: redis-server --bind nacos-service-redis4014 --port 7379 --appendonly yes
    ports:
      - "7379:6379"
    volumes:
      - ~/Docker-sharing/nacos-service/nacos-service-redis4014/data:/data
    networks:
      - nacos-common
    depends_on:
      nacos:
        condition: service_started

  nacos-service-mysql:
    container_name: nacos-service-mysql57
    image: nacos/nacos-mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ssm_explore
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "4306:3306"
    volumes:
      - ~/Docker-sharing/nacos-service/nacos-service-mysql57/data/db:/var/lib/mysql
    networks:
      - nacos-common
    depends_on:
      nacos:
        condition: service_started

  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - ~/Docker-sharing/nacos-service/nacos/standalone-logs/:/home/nacos/logs
      - ~/Docker-sharing/nacos-service/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8849:8848"
      - "9848:9848"
      - "9555:9555"
    depends_on:
      mysql:
        condition: service_started
    networks:
      - nacos-common
  mysql:
    container_name: mysql
    image: nacos/nacos-mysql:5.7
    env_file:
      - ../env/nacos-mysql.env
    volumes:
      - ~/Docker-sharing/nacos-provider/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - nacos-common

networks:
  nacos-common:
    driver: bridge