POST {{host}}/generic/follow
Content-Type: application/json

{
    "follows": {
        "headless": "hello world"
    }
}

###
POST {{host}}/generic/wrapped-request-body
Content-Type: application/json

{
    "wrapped": {
        "headless": "hello world"
    }
}

###
POST {{host}}/common/ping/1504042494465683457
Content-Type: application/json
body: {{bodyBase64Encode}}

###
POST {{host}}/common/base64/encode/{{bodyPlaintext}}
Content-Type: application/json
Accept: application/json

> {%
 client.global.set("bodyBase64Encode", response.body.data)
 %}

###
GET {{host}}/actuator/health
Accept: application/json

###
GET {{host}}/actuator/info
Accept: application/json

###
POST {{host}}/actuator/refresh
Accept: application/json
