---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yooonn.
--- DateTime: 2022/4/3 23:33
---

---@param KEYS table
---@param ARGV table
local function fn(KEYS, ARGV)
    if (redis.call('exists', KEYS[1]) == 0) then
        redis.call('hIncrBy', KEYS[1], ARGV[2], 1);
        redis.call('pExpire', KEYS[1], ARGV[1]);
        return nil;
    end ;
    if (redis.call('hExists', KEYS[1], ARGV[2]) == 1) then
        redis.call('hIncrBy', KEYS[1], ARGV[2], 1);
        redis.call('pExpire', KEYS[1], ARGV[1]);
        return nil;
    end ;
    return redis.call('pTtl', KEYS[1])
end

return fn({ 'hello-test' }, { '30000', '51' })