#!/usr/bin/env sh
# author: yongjiang

. color-header

# functions
printCurrentBranch() {
    echo "${GREEN}current branch: ${BLUE}$1${RESET}"
}

# contents
currentBranchName=$(git symbolic-ref --short HEAD)
opt=$1

printCurrentBranch "${currentBranchName}"

if [ "dao" = "${opt}" ]; then
    ./mvnw clean compile -f ./base/pom.xml
else
    opt='projects'
    ./mvnw clean compile -f ./pom.xml
fi

exit 0
