@startmindmap
* <&folder>   /
**[#orange] <&folder>   /bin
*** <&text>   存放着最常用的程序和指令.

** <&folder>   /boot
*** <&text>   存放的启动Linux 时使用的内核文件, 包括连接文件以及镜像文件.

** <&folder>   /dev
***: <&text>   Device(设备)的缩写, 存放的是Linux的外部设备. **注意: **
在Linux中访问设备和访问文件的方式是相同的.;

**[#orange] <&folder>   /etc
***: <&text>   存放**所有**的系统需要的**配置文件**和**子目录列表, **更改
目录下的文件可能会导致系统不能启动;

**[#salmon] <&folder>   /home
*** <&text>   用户的主目录, 以用户的账号命名的.

**[#peru] <&folder>   /lib
***: <&text>   存放基本代码库 (比如c++库), 其作用类似于Windows里的DLL文件.
几乎所有的应用程序都需要用到这些共享库.;

** <&folder>   /lost+found
*** <&text>   一般情况下为空的, 系统非法关机后, 这里就存放一些文件.

** <&folder>   /media
*** <&text>   类windows的**其他设备,**例如U盘、光驱等等, 识别后linux会把设备放到这个目录下.

** <&folder>   /mnt
*** <&text>    临时挂载别的文件系统的, 我们可以将光驱挂载在/mnt/上, 然后进入该目录就可以查看光驱里的内容了.

**[#peru] <&folder>   /opt
*** <&text>   默认是空的, 我们安装额外软件可以放在这个里面.

**[#peru] <&folder>   /proc
***: <&text>   管理**内存空间！**虚拟的目录, 是系统内存的映射, 我们可以直接访问这个目录来, 获取系统信息.
这个目录的内容不在硬盘上而是在内存里, 我们也可以直接修改里面的某些文件来做修改.;

**[#salmon] <&folder>   /root
*** <&text>   系统管理员的用户主目录.

**[#orange] <&folder>   /sbin
*** <&text>    只有系统管理员能使用的程序和指令.

** <&folder>   /selinux
***: <&text>   这个目录是 Redhat/CentOS 所特有的目录, Selinux 是一个安全机制, 类似于 windows 的防火墙,
但是这套机制比较复杂, 这个目录就是存放selinux相关的文件的.;

** <&folder>   /srv
*** <&text>   存放服务启动后需要提取的数据**(不用服务器就是空)**

** <&folder>   /sys
***: <&text>   这是linux2.6内核的一个很大的变化.该目录下安装了2.6内核中新出现的一个文件系统
sysfs. sysfs文件系统集成了下面3种文件系统的信息: 针对进程信息的proc文件系统, 针对设备的devfs
文件系统以及针对伪终端的devpts文件系统.该文件系统是内核设备树的一个直观反映. 当一个内核对象被创
建的时候, 对应的文件和目录也在内核对象子系统中.;

**[#peru] <&folder>   /temp
*** <&text>   这个目录是用来存放一些临时文件的.

**[#salmon] <&folder>   /usr
***: <&text>   Unix Shared Resource. 用户的很多应用程序和文件都放在这个目录下,
类似于windows下的program files目录.;

**[#salmon] <&folder>   /usr/bin
*** <&text>   系统用户使用的应用程序与指令.

**[#salmon] <&folder>   /usr/sbin
*** <&text>   超级用户使用的比较高级的管理程序和系统守护程序.

**[#salmon] <&folder>   /usr/src
*** <&text>   通常存放源代码. 内核源代码默认的放置目录.

**[#orange] <&folder>   /var
*** <&text>   存放经常修改的数据, 比如程序运行的日志文件 (/var/log 目录下).

** <&folder>   /run
***: <&text>   是一个临时文件系统, 存储系统启动以来的信息. 当系统重启时, 这个目录下的文件应该被删掉或清除.
如果你的系统上有 /var/run 目录, 应该让它指向 run.;

@endmindmap
