@startmindmap

skinparam backgroundColor #EEEBDC

<style>
mindmapDiagram {
    node {
        FontSize 18
            FontStyle bold
            FontName Aapex
    }
}
</style>

*[#lightblue] U-write.**zip**  <&folder>
**[#lightblue] player.**zip**  <&folder>
***_ <&file>
***_ <&file>
***_ ...

**[#lightblue] resource.**zip**  <&folder>
***_ <&file>
***_ <&file>
***_ <&file> ...
*** <&file> play order

** <&file>  config.conf, **encrypted**

@endmindmap