==== tar advance

最常用的打包命令是 tar，使用 tar 程序打出来的包我们常称为 tar 包，tar 包文件的命令通常都是以 .tar 结尾的。生成 tar 包后，就可以用其它的程序来进行压缩了，所以首先就来讲讲 tar 命令的基本用法。

tar 命令的选项有很多(用 man tar 可以查看到)，但常用的就那么几个选项，下面来举例说明一下：

===== 1. 基础

====== 1) 将所有 .jpg 的文件打成一个名为 all.tar 的包。

> -c 是表示产生新的包，-f 指定包的文件名。

[source,shell script]
----
tar -cf all.tar *.jpg
----

====== 2) 将所有 .gif 的文件增加到 all.tar 的包里面去，-r 是表示增加文件的意思。

[source]
----
tar -rf all.tar *.gif
----

====== 3) 更新原来 tar 包 all.tar 中 logo.gif 文件，-u 是表示更新文件的意思。

[source]
----
tar -uf all.tar logo.gif
----

====== 4) 列出 all.tar 包中所有文件，-t 是列出文件的意思。

[source]
----
tar -tf all.tar
----

====== 5) 解出 all.tar 包中所有文件，-x 是解开的意思。

[source]
----
tar -xf all.tar
----

以上就是 tar 的最基本的用法。为了方便用户在打包解包的同时可以压缩或解压文件，tar 提供了一种特殊的功能。这就是 tar 可以在打包或解包的同时调用其它的压缩程序，比如调用 gzip、bzip2 等。

===== 2. tar调用

gzip 是 GNU 组织开发的一个压缩程序，.gz 结尾的文件就是 gzip 压缩的结果。与 gzip 相对的解压程序是 gunzip。tar 中使用 -z 这个参数来调用gzip。下面来举例说明一下：

====== 将所有 .jpg 的文件打成一个 tar 包，并且将其用 gzip 压缩

____
生成一个 gzip 压缩过的包，包名为 all.tar.gz。
____


[source]
----
tar -czf all.tar.gz *.jpg
----

====== 将上面产生的包解开。

[source]
----
tar -xzf all.tar.gz
----

===== 3. tar 调用 bzip2

bzip2 是一个压缩能力更强的压缩程序，.bz2 结尾的文件就是 bzip2 压缩的结果。

与 bzip2 相对的解压程序是 bunzip2。tar 中使用 -j 这个参数来调用 gzip。下面来举例说明一下：

====== 将所有 .jpg 的文件打成一个 tar 包，并且将其用 bzip2 压缩

____
生成一个 bzip2 压缩过的包，包名为 all.tar.bz2
____

[source]
----
tar -cjf all.tar.bz2 *.jpg
----

====== 将上面产生的包解开。

[source]
----
tar -xjf all.tar.bz2
----

===== 4. tar 调用 compress

compress 也是一个压缩程序，但是好象使用 compress 的人不如 gzip 和 bzip2 的人多。.Z 结尾的文件就是 bzip2 压缩的结果。与 compress 相对的解压程序是 uncompress。tar 中使用 -Z 这个参数来调用 compress。下面来举例说明一下：

====== 将所有 .jpg 的文件打成一个 tar 包，并且将其用 compress 压缩

> 生成一个 uncompress 压缩过的包，包名为 all.tar.Z。

[source]
----
tar -cZf all.tar.Z *.jpg
----

====== 将上面产生的包解开。

[source]
----
tar -xZf all.tar.Z
----

===== 5. 总结

有了上面的知识，你应该可以解开多种压缩文件了，下面对于 tar 系列的压缩文件作一个小结：

====== 1) 对于.tar结尾的文件

[source]
----
tar -xf all.tar
----

====== 2) 对于 .gz 结尾的文件

[source]
----
gzip -d all.gz
gunzip all.gz
----

====== 3) 对于 .tgz 或 .tar.gz 结尾的文件

[source]
----
tar -xzf all.tar.gz
tar -xzf all.tgz
----

====== 4) 对于 .bz2 结尾的文件

[source]
----
bzip2 -d all.bz2
bunzip2 all.bz2
----

====== 5) 对于 tar.bz2 结尾的文件

[source]
----
tar -xjf all.tar.bz2
----

====== 6) 对于 .Z 结尾的文件

[source]
----
uncompress all.Z
----

====== 7) 对于 .tar.Z 结尾的文件

[source]
----
tar -xZf all.tar.z
----

===== 6. .zip 和 .rar

另外对于 Windows 下的常见压缩文件 .zip 和 .rar，Linux 也有相应的方法来解压它们：

====== 1) 对于 .zip

linux 下提供了 zip 和 unzip 程序，zip 是压缩程序，unzip 是解压程序。它们的参数选项很多，这里只做简单介绍，依旧举例说明一下其用法：

===== 将所有 .jpg 的文件压缩成一个 zip 包

[source]
----
zip all.zip *.jpg
----

===== 将 all.zip 中的所有文件解压出来。

[source]
----
unzip all.zip
----

====== 2) 对于 .rar

要在 linux 下处理 .rar 文件，需要安装 RAR for Linux。下载地址：http://www.rarsoft.com/download.htm，下载后安装即可。

[source]
----
tar -xzpvf rarlinux-x64-5.6.b5.tar.gz
cd rar
make
----

这样就安装好了，安装后就有了 rar 和 unrar 这两个程序，rar 是压缩程序，unrar 是解压程序。它们的参数选项很多，这里只做简单介绍，依旧举例说明一下其用法

====== 将所有 .jpg 的文件压缩成一个 rar 包，名为 all.rar

> 该程序会将 .rar 扩展名将自动附加到包名后。

[source]
----
rar a all *.jpg
----

===== 将 all.rar 中的所有文件解压出来：

[source]
----
unrar e all.rar
----

==== 扩展内容

tar

[source]
----
-c: 建立压缩档案
-x：解压
-t：查看内容
-r：向压缩归档文件末尾追加文件
-u：更新原压缩包中的文件
----

这五个是独立的命令，压缩解压都要用到其中一个，可以和别的命令连用但只能用其中一个。下面的参数是根据需要在压缩或解压档案时可选的。

[source]
----
-z：有gzip属性的
-j：有bz2属性的
-Z：有compress属性的
-v：显示所有过程
-O：将文件解开到标准输出
----

下面的参数 -f 是必须的:

[source]
----
-f: 使用档案名字，切记，这个参数是最后一个参数，后面只能接档案名。
----



将所有 .jpg 的文件打成一个名为 all.tar 的包。-c 是表示产生新的包，-f 指定包的文件名。

[source]
----
tar -cf all.tar *.jpg
----



将所有 .gif 的文件增加到 all.tar 的包里面去。-r 是表示增加文件的意思。

[source]
----
tar -rf all.tar *.gif
----



更新原来 tar 包 all.tar 中 logo.gif 文件，-u 是表示更新文件的意思。

[source]
----
tar -uf all.tar logo.gif
----



列出 all.tar 包中所有文件，-t 是列出文件的意思。

[source]
----
tar -tf all.tar
----



解出 all.tar 包中所有文件，-x 是解开的意思。

[source]
----
tar -xf all.tar
----



压缩

[source]
----
tar –cvf jpg.tar *.jpg       // 将目录里所有jpg文件打包成 tar.jpg
tar –czf jpg.tar.gz *.jpg    // 将目录里所有jpg文件打包成 jpg.tar 后，并且将其用 gzip 压缩，生成一个 gzip 压缩过的包，命名为 jpg.tar.gz
tar –cjf jpg.tar.bz2 *.jpg   // 将目录里所有jpg文件打包成 jpg.tar 后，并且将其用 bzip2 压缩，生成一个 bzip2 压缩过的包，命名为jpg.tar.bz2
tar –cZf jpg.tar.Z *.jpg     // 将目录里所有 jpg 文件打包成 jpg.tar 后，并且将其用 compress 压缩，生成一个 umcompress 压缩过的包，命名为jpg.tar.Z
rar a jpg.rar *.jpg          // rar格式的压缩，需要先下载 rar for linux
zip jpg.zip *.jpg            // zip格式的压缩，需要先下载 zip for linux
----



解压

[source]
----
tar –xvf file.tar         // 解压 tar 包
tar -xzvf file.tar.gz     // 解压 tar.gz
tar -xjvf file.tar.bz2    // 解压 tar.bz2
tar –xZvf file.tar.Z      // 解压 tar.Z
unrar e file.rar          // 解压 rar
unzip file.zip            // 解压 zip
----

总结

[source]
----
1、*.tar 用 tar –xvf 解压
2、*.gz 用 gzip -d或者gunzip 解压
3、*.tar.gz和*.tgz 用 tar –xzf 解压
4、*.bz2 用 bzip2 -d或者用bunzip2 解压
5、*.tar.bz2用tar –xjf 解压
6、*.Z 用 uncompress 解压
7、*.tar.Z 用tar –xZf 解压
8、*.rar 用 unrar e解压
9、*.zip 用 unzip 解压
----

:bookmark: from [here](https://www.runoob.com/w3cnote/linux-tar-gz.html)