#!/usr/bin/expect

set timeout -1
set project iscar
set container_ip 10.100.211.42
set host_ip 10.100.208.6

spawn ssh jps

expect {
    "Opt> " { send "$host_ip\r"}
}
expect {
    "~]$ " { send "cd /data/logs/$project\_$container_ip\r" }
}
interact