#!/usr/bin/expect

set timeout -1
set project iscar
set container_ip 10.100.206.127
set host_ip 10.100.192.28

spawn ssh jps

expect {
    "Opt> " { send "$host_ip\r"}
}
expect {
    "~]$ " { send "cd /data/logs/$project\_$container_ip\r" }
}
interact