---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yooonn.
--- DateTime: 2022/4/3 21:49
---

local function fun1()
    local a = 0
    return type(a)
end

local function fun2()
    local a = KEYS[1]
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)

    --这里的resp的类型是table，可见redis的set返回的是table
    return type(resp)
end

local function fun3()
    local a = KEYS[1]
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)
    --出错
    return resp[1]
end

local function fun4()
    local a = KEYS[1]
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)
    --next(resp) 是字符串ok
    return next(resp)
end

local function fun5()
    local a = KEYS[1]
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)
    --type(next(resp))的值是string
    return type(next(resp))
end

local function fun6()
    local a = KEYS[1]
    redis.call('set', a, 'hello')
    local resp = redis.call('del', a)
    return type(resp)
end

local function fun7()
    local a = KEYS[1]
    redis.call('zAdd', a, '100', 'hello')
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)
    --type(next(resp))的值是string
    return resp
end

local function fun8()
    local a = KEYS[1]
    redis.call('zAdd', a, '100', 'hello')
    local resp = redis.call('set', a, 'hello')
    redis.call('del', a)
    --type(next(resp))的值是string
    return resp
end

return fun7()
