version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-longuse-5
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ~/sharing/mysql-long-5.7/data/db:/var/lib/mysql
      - ~/sharing/mysql-long-5.7/data/conf:/etc/mysql/conf.d
      - ~/sharing/mysql-long-5.7/log:/var/log/mysql
