version: '3'
services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql-longuse-8
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
    volumes:
      - ~/sharing/mysql-long-8.0.16/data/db:/var/lib/mysql
      - ~/sharing/mysql-long-8.0.16/data/conf:/etc/mysql/conf.d
      - ~/sharing/mysql-long-8.0.16/log:/var/log/mysql
