version: '3'
services:
  es01:
    image: elasticsearch:7.9.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap_memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/use/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  es02:
    image: elasticsearch:7.9.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap_memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/use/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic

  es03:
    image: elasticsearch:7.9.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap_memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512M"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/use/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic
  kib01:
    image: kibana:7.9.3
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge