version: '3'
services:
  mysql:
    image: redis:6.0
    container_name: rd-longuse-6.0
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    volumes:
      - ~/sharing/redis-long-6.0/data:/data #数据文件挂载
