@startuml

' 标题支持creole formatting
'   This is **bold**
'   This is //italics//
'   This is ""monospaced""
'   This is --stroked--
'   This is __underlined__
'   This is ~~waved~~
' title单行时使用title，多行title可使用title, end title

title
__Simple__ **communication** example
  <u>Simple</u> communication example
 on <i>several</i> lines and using <font color=red>html</font>
 This is hosted by <img:sourceforge.jpg>
end title

Alice -> Bob: Authentication Request
Bob -> Alice: Authentication Response

@enduml