@startuml

' The keyword autonumber is used to automatically add number to messages.
' 关键词autonumber被用于自动地将序号添加到消息上

autonumber
Bob -> Alice : Authentication Request
Bob <- Alice : Authentication Response

' advanced usage
autonumber
j -> y : Authentication Request
j <- y : Authentication Response

autonumber 15
j -> y : Another authentication Request
j <- y : Another authentication Response

autonumber 40 10
j -> y : Yet another authentication Request
j <- y : Yet another authentication Response


' You can specify a format for your number by using between double-quote.
' 可以用双引号为序号定制一个格式

' The formatting is done with the Java class DecimalFormat (0 means digit, # means digit and zero if absent).
' 格式采用java.text.DecimalFormat，其中0表示数字，#表示数字（如果没有则为0）

' You can use some html tag in the format.
' 格式中可以用html标签

' 可以使用autonumber stop来停止此次的序号

autonumber "<b>[000]"
b -> a : Authentication Request
b <- a : Authentication Response

autonumber 15 "<b>(<u>##</u>)"
b -> a : Another authentication Request
b <- a : Another authentication Response

autonumber stop
b -> a : dummy

autonumber 40 10 "<font color=red><b>Message 0  "
b -> a : Yet another authentication Request
b <- a : Yet another authentication Response



@enduml