@startuml

' 控制符号的格式
' true is default value, so you can ignore this line
skinparam guillemet true
participant "Famous Bob" as Bob << Generated >>
participant Alice << (C,#ADD1B2) Testable >>

Bob->Alice: First message


@enduml