---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yongjiang.
--- DateTime: 2022/4/3 21:49
---


local function keysType()
    local a = type(redis.call('keys', '*'));
    return a;
end

---@param keys table
local function delKeysOf(keys)
    local a = redis.call('keys', keys[1]);
    for k, v in pairs(a) do
        redis.call('del', v)
    end
end

--return keysType();

delKeysOf({ '*' })
