# @name watch
POST {{aio}}/watch
Accept: application/json
Content-Type: application/json

{
    "prop_key": "flying.str"
}

###
# @name ping
POST {{aio}}/ping
Accept: application/json
Content-Type: application/json

{
    "params": {
        "hello": "foo",
        "foo": 12
    }
}

###
# @name refresh nacos token
< {%
    client.log(client.global.get("NACOS_ACCESS_TOKEN"));
%}
POST {{NACOS}}/nacos/v1/auth/login
Content-Type: application/x-www-form-urlencoded

username=nacos&password=nacos

> {%
    let token = String(response.body.accessToken)
    client.assert(token != null && token.length > 0, "access token is empty")
    client.log("hi :" + response.body.accessToken)
    client.global.set("NACOS_ACCESS_TOKEN", response.body.accessToken)
%}

###
GET {{NACOS}}/nacos/v1/cs/configs?
        accessToken={{NACOS_ACCESS_TOKEN}}&
        dataId={{AIO_NACOS_DATA_ID}}&
        group={{AIO_NACOS_GROUP}}&
        namespaceId={{AIO_NACOS_NAMESPACE}}&
        tenant={{AIO_NACOS_NAMESPACE}}&
        show=all&
        username=nacos

###
