GET {{aio}}/info
Accept: application/json

###
GET {{aio}}/env
Accept: application/json

###
GET {{aio}}/beans
Accept: application/json

###
GET {{aio}}/mappings
Accept: application/json

###
GET {{aio}}/nacosconfig
Accept: application/json

###
