GET {{NACOS}}/nacos/v1/cs/configs?accessToken={{NACOS_ACCESS_TOKEN}}&dataId={{AIO_NACOS_DATA_ID}}&group={{AIO_NACOS_GROUP}}&namespaceId={{AIO_NACOS_NAMESPACE}}&tenant={{AIO_NACOS_NAMESPACE}}&show=all&username=nacos

###
POST {{NACOS}}/nacos/v1/cs/configs?accessToken={{NACOS_ACCESS_TOKEN}}&username=nacos
Content-Type: application/x-www-form-urlencoded

dataId={{AIO_NACOS_DATA_ID}}&group={{AIO_NACOS_GROUP}}&namespaceId={{AIO_NACOS_NAMESPACE}}&tenant={{AIO_NACOS_NAMESPACE}}&show=all&

###
POST {{NACOS}}/nacos/v1/auth/login
Content-Type: application/x-www-form-urlencoded

username=nacos&password=nacos

> {% client.global.set("accessToken", response.body.json.accessToken); %}

###
POST {{aio}}/watch
Accept: application/json

###

GET {{aio}}/info
Accept: application/json

###
GET {{aio}}/env
Accept: application/json

###
GET {{aio}}/beans
Accept: application/json

###
GET {{aio}}/mappings
Accept: application/json

###
GET {{aio}}/nacosconfig
Accept: application/json

###
GET {{aio}}/health
Accept: application/json

###
